// frontend/ndp-frontend/src/components/Header.jsx
﻿import React from 'react';
import { Link } from 'react-router-dom';

const Header = () => {
  return (
    <div className="container py-4">
      <div className="text-center">
        <Link to="/" className="text-decoration-none">
          <h1 className="display-4 fw-bold text-white mb-2">
            📚 NDP Library
          </h1>
          <p className="lead text-white-50 mb-0">
            Digital Book Management System
          </p>
        </Link>
      </div>
    </div>
  );
};

export default Header;

// frontend/ndp-frontend/src/app/shared/components/header/header.component.ts
﻿import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: true,
  template: `
    <header class="bg-blue-600 text-white p-4">
      <div class="container mx-auto">
        <h1 class="text-2xl font-bold">NDP Library</h1>
      </div>
    </header>
  `
})
export class HeaderComponent {}
