// frontend/ndp-frontend/src/app/shared/components/footer/footer.component.ts
﻿import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  template: `
    <footer class="bg-gray-800 text-white p-4 mt-8">
      <div class="container mx-auto text-center">
        <p>&copy; 2026 NDP Library. All rights reserved.</p>
      </div>
    </footer>
  `
})
export class FooterComponent {}

// frontend/ndp-frontend/src/components/Footer.jsx
﻿import React from 'react';
import { Link } from 'react-router-dom';

const Footer = () => {
  return (
    <footer className="mt-auto py-4">
      <div className="container">
        <div className="row">
          <div className="col-md-6">
            <p className="text-white-50 mb-0">
              <span className="me-2">📚</span>
              NDP Library Management System
            </p>
          </div>
          <div className="col-md-6 text-md-end">
            <p className="text-white-50 mb-0">
              &copy; {new Date().getFullYear()} All rights reserved
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
